name: Build and Release LavenderHook

on:
  push:
    tags:
      - 'v*.*.*.*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake
        run: cmake -B build -S LavenderHook -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build

      - name: Delete existing release
        run: gh release delete ${{ github.ref_name }} --yes
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/LavenderHook.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
