name: Build and Release LavenderHook

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read Version File
        id: get_version
        run: |
          $ver = Get-Content Version
          echo "VERSION=$ver" >> $env:GITHUB_OUTPUT
        shell: powershell

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake
        run: cmake -B build -S LavenderHook -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build

      - name: Update Single Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: LavenderHook
          name: "${{ steps.get_version.outputs.VERSION }} LavenderHook"
          body: ""
          files: build/LavenderHook.dll
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}